### ISSUE TITLE
Exception in runtime: java.lang.IllegalAccessException: no such constructor: org.jetbrains.jewel.bridge.SwingBridgeService.<init>(CoroutineScope)void/invokeSpecial

### ISSUE THREAD

**Issue by overpas** [JetBrains/jewel#268]
I'm trying to use it in an intellij plugin like so:
```kotlin
@OptIn(ExperimentalJewelApi::class)
fun myPluginPanel(): JComponent = JewelComposePanel {
    SwingBridgeTheme {
        Text("Hello Swing!")
    }
}
```
however the following exceptions are thrown in runtime when the actual code is reached:
```
Caused by: java.lang.IllegalAccessException: no such constructor: org.jetbrains.jewel.bridge.SwingBridgeService.<init>(CoroutineScope)void/invokeSpecial
Caused by: java.lang.LinkageError: bad method type alias: (CoroutineScope)void not visible from class org.jetbrains.jewel.bridge.SwingBridgeService
```
Any idea how to fix this? I know the library is not ready for use yet, but Swing and UI DSL V1 and V2 are such a pain.

I'm using:
- JVM 17
- Intellij Platform version 232.8660.185
- Jewel 0.11.0
- Jewel LaF Bridge 0.11.0-ij-232
- Compose 1.5.11

**Comment by lamba92** [comment]
Hi! Can you please check if in the coroutines jar leaked inside your classpath? 

There are some libraries that are already present in the IntelliJ platform at runtime, coroutines is one of them. If you also provide a jar with the same symbols, in your case `CoroutineScope`, the class loader will be terribly confused and will just give up. 

To check if coroutines are there, go in `build/idea-sandbox/plugins/plugin/lib` and check if there is a jar that come from coroutines. If so, you need to exclude coroutines from the dependencies you are importing, like:

```kotlin
dependencies {
   implementation("my.lib:a-lib:1.0.0") {
     exclude(group = "org.jetbrains.kotlinx" module = "kotlinx-coroutines-core")
     // add any other coroutine library that you see!
  }
}
```

It is not always easy to go from name of the jar to actual maven coordinates to exclude, since the name of the jar can be arbitrary, but it usually is equal to the `artifactId`/`module` of the library, it is up to you to know what is the `groupId`.

Also, there is no real list of which libraries are already in the IJ platform, so expect this to happen often for JetBrains libraries, such as Ktor or kotlinx-datetime.

**Comment by CodeIdeal** [comment]
I have the same issue. And i checked the idea-sandbox dir, there is no `kotlinx-coroutines-core` jar file.

![image](https://github.com/JetBrains/jewel/assets/15637613/2971dfa4-9b1e-4075-9e6d-b58136bfde3c)

**Comment by robercoding** [comment]
My Intellij Plugin had a dependency on a project that was using coroutines dependency. After excluding it, it worked!

**Comment by rock3r** [comment]
Since the OP has never replied, I am going to close this issue and assume it's been fixed. Please file a new issue if you have any further problems.
