### ISSUE TITLE
Consider deleting `intermediateMarkdown` strings in the intermediate representation and use CommonMark `Node` trees instead

### ISSUE THREAD

**Issue by obask** [JetBrains/jewel#329]
An example with working samples is located in 3df1cccc96211384a767b88a70cfa21cdca3ac9f.
This should improve parsing speed and reduce GC overload. Also, the biggest improvement will be in markdown extensions API since we'll be able to reuse CommonMark patterns and only extend it in for rendering.

Please let me know what you think!

PS of course string rendering code could be later cleaned up too, this is a minimal set of changes making samples to run

**Comment by rock3r** [comment]
It's kinda funny cause as I was writing the initial version I went back and forth several times between the two versions, passing along the Node vs only a string of the inline markdown. I ended up on the string because I didn't think extensions would need to access the underlying Node(s) — if they did, most of the block-level parsing would be duplicated effort. I thought, in that case the proper fix is to make sure all the required info is there in our own block level models. The added benefit is that you can pretty easily swap out Commonmark for another parser if you desire, for example to support other Markdown-like formats such as reText (not that I was planning to).

Do you have perf improvement numbers? Those could be the deciding factor, if the difference is significant enough.

However, I think a bigger perf improvement would come if we somehow managed to support incremental updating, e.g., by tracking with block(s) the user is editing in the text area, and only re-processing those

**Comment by rock3r** [comment]
Oh and one more reason I forgot to mention — block-level models as they are now can easily be made serializable, as they're only made of models we control and primitive types. This might be useful in the future (e.g., if the first parsing step result needs to be stored to disk or sent over network)

**Comment by obask** [comment]
Here are my measurements(this comment is just to preserve benchmark results but I'd like to discuss over a phone about overall approach and if it makes sense at all)...

exact code: https://github.com/obask/jewel/commit/aef1b88c4e562730ffca186d2dd68251f3993067
a large markdown file for benchmarking(this commit was cherry-picked on top): https://github.com/obask/jewel/blob/7c9345fd2b18158073a0319e2477f5be4ac31fea/samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/markdown/MarkdownCatalog.kt

Initial measurements for rendering:
-----------------------------
method: DefaultMarkdownBlockRenderer.render
### COMMONMARK:

Call count: 10,000
Total wall time: 363 ms

**Average wall time: 36 μs**
Max wall time: 2,931 μs

MAIN:

Call count: 10,011
Total wall time: 507 ms

**Average wall time: 50 μs**
Max wall time: 4,925 μs

Measurments for typing:
---------------

method: MarkdownProcessor.processMarkdownDocument

### commonmark typing
Call count: 10
Total wall time: 498 ms

**Average wall time: 49 ms**
Max wall time: 66 ms
<img width="1281" alt="commonmark-api-typing" src="https://github.com/JetBrains/jewel/assets/13053173/38013459-b9c5-4243-a5e5-3588a2ea590b">

### MAIN typing 
Call count: 10
Total wall time: 736 ms

**Average wall time: 73 ms**
Max wall time: 101 ms
<img width="1281" alt="master-typing" src="https://github.com/JetBrains/jewel/assets/13053173/e629f066-4f66-41ce-b9ee-7f12362797c9">

A video with my testing workflow: https://drive.google.com/file/d/14uymTjw7z5T6FMfsU7ZHmeV2xldkJmqF/view
e.g. scrolling a whole file slowly and then typing numbers from 1 to 10 and waiting for each frame to render
