### ISSUE TITLE
Cannot navigate out of selectableLazyColumn using keyboard

### ISSUE THREAD

**Issue by YasserDbeis** [JetBrains/jewel#347]
When using the keyboard to navigate the "Compose" tab in the ide-sample, I can navigate from the search bar > three dot menu > the list of releases all with the tab button. However, once I am in the release list, I cannot tab or shift+tab out of it.

I also tried adding a `DefaultButton` to the right panel (the details panel) to see if I could tab into it, but this did not work either (see attachament).

This was reproducible as of Jewel 0.17.0.
![3wrv7kNQyGrb6fD](https://github.com/JetBrains/jewel/assets/54920066/54256209-893d-4391-8840-890f89acd7a1)

**Comment by fscarponi** [comment]
I am aware of this behavior, so far no fix has been introduced because this behavior is part of a larger issue that is still to be addressed and resolved: the management of keybindings and coexistence with those of the platform. 
At the moment, I believe that it is generally not possible to manage keybinding with behavior of the type: I want to intercept keybindings (a) and (b), let the others be handled by the platform. Perhaps we can think of trying to fix this specific case (very important) and then later reevaluate the underlying problem.

One idea could be to handle the tab in DefaultKeyBindings, to manually pass the focus to the next component.
I'm open to any other ideas!

**Comment by fscarponi** [comment]
https://github.com/JetBrains/jewel/pull/348

**Comment by fscarponi** [comment]
fIxed in #348

**Comment by YasserDbeis** [comment]
If the user has not selected anything from the list yet, and navigates to the list using tab, then the arrow keys do not seem to be detected. Are you also encountering this post fix?

**Comment by rock3r** [comment]
Fabrizio is off sick, this may take some time to get an answer from him on.

PS: in general if the bug is not the exact same as before I'd rather open a new issue than reopen a fixed one

**Comment by YasserDbeis** [comment]
Sounds good--I will open a new bug.
