### ISSUE TITLE
LazyPopupMenu

### ISSUE THREAD

**Issue by francisconoriega** [JetBrains/jewel#518]
There is no lazy version of PopupMenu, which makes it's performance pretty terrible for longer lists. You can internally use a LazySelectableList, but it becomes cumbersome and you lose a PopupMenuItem styling, most notable the hovering

**Comment by rock3r** [comment]
I reckon a good approach to this would be decoupling the popup and its styling from the contents, and then provide the existing non-lazy menu (it's not lazy because _actual_ menus rarely have more than a few dozen entries) on top of it, leaving others the possibility to provide their own popup contents. What do you think?

**Comment by francisconoriega** [comment]
yeah, that would also work, perhaps SelectableItem can be independent of the Menu, and just provides style? Either as a Composable or as a modifier, and then you could use it in both selectable menu, or inside a LazySelectableColumn

**Comment by rock3r** [comment]
We're probably going to revisit a number of things re: selectable lazy list and tree view, but I'm not sure how the item styling will fall in there. It may make sense to have a selectableBackground modifier maybe. A lot of variables to consider

**Comment by rock3r** [comment]
Closing in favour of #528
