### ISSUE TITLE
defaultTextStyle lineheight does't match IDE

### ISSUE THREAD

**Issue by francisconoriega** [JetBrains/jewel#585]
When showing blocks of text, IJ seems to be using a larger lineheight (seems like the default is 22.sp but it scales with font size).

This can be seen in multiple areas such as the kdoc tooltip, or the full documentation panel. The defaultTextStyle has no lineheight set at all, and is much more compact.

I'm not sure if this is the correct logic, but if you multiply the default font size of 13 by 1.69, you get 22, which is what it seems to be using at that size.

![image](https://github.com/user-attachments/assets/b4f7e488-3e63-41ed-a893-075ac1289d24)
![image](https://github.com/user-attachments/assets/70a85c41-dd39-4f4d-a8d9-3892db132d95)

**Comment by rock3r** [comment]
I checked the `StylesheetUtil.getDefaultStylesheet()` that Swing uses for styling the HTML text, and there isn't any mention of line height for text:

<img width="667" alt="image" src="https://github.com/user-attachments/assets/2eddba91-6029-4ff4-b21f-206dfe073839">

I looked pretty much everywhere I could think of in the platform and did not find any line height indication; I assume it's somewhere in Swing's bowels.

The correct line height multiplier (on macOS) seems to be 1.3, so I'll apply that to all non-editor/console text styles we have in Jewel.

**Comment by rock3r** [comment]
I'm releasing 0.24.1 with this fix

**Comment by rock3r** [comment]
Oh and by the way, looking once again to the screenshots above — the line height is clearly bigger than 1.3x, it looks almost 2x, but that is most likely because the inline code has a background and padding which increases the line height. Swing's text layout engine then uses the same line height everywhere in the component, apparently. I don't know if the same happens in Compose, but regardless, it's not something we can tweak. I'm not going to rewrite the text layout engine :)
