### ISSUE TITLE
EditorColors missing from colorPalette

### ISSUE THREAD

**Issue by francisconoriega** [JetBrains/jewel#586]
IntUI figma kit also defines EditorColors, but these are missing from the current colorPalette. Should we add them?

<img width="845" alt="image" src="https://github.com/user-attachments/assets/20705e32-9130-4b65-9438-fafce7578f5f">

**Comment by rock3r** [comment]
We don't have editor colours because they are only needed for syntax highlighting, which we don't have yet. We're working on that, and we'll have a way to represent EditorScheme, too, but we can't do it in a vacuum.

Besides, it's not a trivial thing as the figma specs would make it seem, since in the EditorScheme the colours can be, and are, different between languages. And different languages have different colour keys, which can, and do, use additional colours.

**Comment by rock3r** [comment]
I'm going to close this for now — we are not planning to add EditorColors to the palette separately from supporting a basic, lexer-based syntax highlighting in standalone, and that's happening in a vague, soon-but-not-very-soon future :)
