### ISSUE TITLE
AllIconsKeys should use the new Path as structure, instead of the old one

### ISSUE THREAD

**Issue by francisconoriega** [JetBrains/jewel#604]
Currently, `AllIconKeys` are organized based on the old path structure, which makes it more difficult than necessary to locate icons, especially when using the website: [https://intellij-icons.jetbrains.design/](https://intellij-icons.jetbrains.design/).

For example, if you try to find the scratches icon, the website provides the following path:
<img width="340" alt="image" src="https://github.com/user-attachments/assets/21d8062c-7f82-4076-99af-63516cbd7470">

However, `AllIconsKeys.FileTypes.Scratches` is not a valid option. You then have to manually inspect the `AllIconKeys` file and eventually discover that it does exist, but under `AllIconsKeys.Scope.Scratches`.

<img width="780" alt="image" src="https://github.com/user-attachments/assets/fe16553f-548e-4984-8f3b-cc5122fbc4af">

### Proposal 1

Introduce a breaking change to update icons to match the **new path**. Since Jewel is based on the new UI, this change aligns well.

### Proposal 2

To avoid a breaking change, we could duplicate the keys under both the old and new paths.

Personally, I believe Option 1 is cleaner and better overall, and updating the usage would be relatively simple and quick.

**Comment by rock3r** [comment]
I think this is a @c5inco question, since he's the master of icons 😄

**Comment by rock3r** [comment]
(my personal opinion is that the website should reflect where icons are in All icons, since that's the one place that's not easy to change, and as a result won't be changed)

**Comment by c5inco** [comment]
Having worked on that IntelliJ icons site myself, and knowing what icons repository and designer handoff process is behind it, I would NOT follow the keys shown on the site very closely to the point our API is dependent on it. Years ago, I made the assumption that an icon key could just follow the directory path, e.g. AllIcons.General.Add. However, the IntelliJ folks don't do that with 100% consistency (as the scratch example points out and the many mappings files in their plugins), which can lead to small discrepancies here and there, where it ends up being best to look at the community source on GitHub as the ultimate source of truth. 

I would actually like to remove that icon key on the site, especially for any set outside `AllIcons` because other icon reference files are not consistently generated in the same way. I'll likely do that shortly since I help maintain the site.

Therefore, I don't think we should adjust Jewel's API at this moment. Also, the paths on that site largely assume you are using the icon in Swing and not Compose, which complicates it further. I can work with the IntelliJ team to improve the site search, with the New UI being default and Jewel being a concept to care about now, but I expect the changes to come next year.
