### ISSUE TITLE
IconButton lacks visual indication in disabled state

### ISSUE THREAD

**Issue by kateliu20** [JetBrains/jewel#633]
Hi, I'm trying to create a text field with an icon button. When using the enabled parameter of the IconButton, only the functionality (clickability) changes, with no visual indication of the disabled state.

I've created a custom modifier function to fade out the button when it's disabled:
<img width="473" alt="Screenshot 2024-10-15 at 1 25 51 PM" src="https://github.com/user-attachments/assets/ca98e208-edc2-408d-aa09-697b34f4af9d">

But when just using the IconButton enabled parameter, there are no changes to how the button looks, only the functionality of if it's clickable or not:
<img width="461" alt="Screenshot 2024-10-15 at 1 28 14 PM" src="https://github.com/user-attachments/assets/67560d3c-acf6-4c89-9572-81ea6a5ebfc0">

Could the default behavior of the IconButton be updated to visually reflect its disabled state? Also, if there's a recommended approach to handle this without a custom function, please advise. Thank you so much!

**Comment by rock3r** [comment]
Hi! You're in charge of handling the icon appearance by design. That is because there are two ways to do it and we don't and can't know for you which one is the one you need:

* Using `ColorFilter.disabled()` (and possibly an `alpha` modifier) to emulate what Swing does to disabled icons
* Using PainterHints and stateful icons (e.g., `myIcon.svg` and `myIconDisabled.svg`)

If you have consistent behaviour in your app wrt handling icons I'd recommend wrapping the `Icon` composable and adding whichever behaviour works for you.
