### ISSUE TITLE
Using AnnotatedString with TextArea

### ISSUE THREAD

**Issue by BFergerson** [JetBrains/jewel#730]
With TextArea(TextFieldValue) deprecated, what is the recommended approach for creating a TextArea with multiple colors? Or is supporting text with various colors no longer supported by TextArea? If so, is there an alternative besides starting from scratch with InputField?

**Comment by rock3r** [comment]
We're mostly depending on what Compose provides in terms of API. We're not going to remove the deprecated value-based API until Compose fixes this shortcoming, since the state-based API doesn't support annotated strings in Compose yet.

So for now you should use the state-based, non deprecated API in most cases, unless you need AnnotatedString buffers in which case you need the old, deprecated but still functional, value-based API.
